# Site settings
title: Shashwat Pandey
role: MS Computer Engineering @ ASU
research_areas: Machine Learning • Statistical Learning Theory • Neural Networks

# Social links
github: https://github.com/shashwatpandey4
twitter: https://x.com/shashwat023
google_scholar: https://scholar.google.com/citations?user=yourid

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"