# Site settings
title: Shashwat Pandey
email: shashwatpandeym.v@gmail.com
description: >-
  Your site description here.
baseurl: "" 
url: "" 
twitter_username: shashwat023
github_username:  Shashwatpandey4

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Collections
collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/
  research:
    output: true
    permalink: /research/:title/
  projects:
    output: true
    permalink: /projects/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      
# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/