// Two prototype figures in Excalidraw style, for comparison against the crisp
// SVG versions already in Part 1. Writes posts/figtest.md.
const fs = require('fs');
const path = require('path');
const { fig, INK, BLUE, ORANGE, GRAY, MUTED, FAINT } = require('./rough.cjs');

// ---------------------------------------------------------------- figure A
// The naive kernel's memory access: one warp, 32 different rows of A.
function naiveAccess() {
  const f = fig(740, 300, 11);
  f.text(0, 16, 'matrix A in memory (row-major)', { size: 13, fill: MUTED });

  const rows = [
    { y: 34, label: 'row 0' },
    { y: 62, label: 'row 1' },
    { y: 90, label: 'row 2' },
    { y: 146, label: 'row 31' },
  ];
  for (const r of rows) {
    f.text(0, r.y + 14, r.label, { size: 13, fill: MUTED });
    f.rect(58, r.y, 470, 18, { fill: '#f4f6f7', fillStyle: 'solid', stroke: FAINT, sw: 1 });
    f.solid(180, r.y, 16, 18, { fill: ORANGE, stroke: ORANGE, sw: 1.2 });
    f.text(552, r.y + 14, 'one fetch', { size: 12, fill: ORANGE });
  }
  f.text(96, 130, '. . .', { size: 16, fill: '#aaaaaa' });
  f.text(180, 130, '. . .', { size: 16, fill: ORANGE });

  f.text(58, 190, 'one row = K floats = 3584 bytes for K=896', { size: 12, fill: MUTED });

  // the punchline
  f.line(20, 208, 720, 208, { stroke: FAINT, sw: 1 });
  f.text(0, 234, 'the warp asked for 32 floats', { size: 14, fill: INK });
  f.solid(258, 221, 36, 16, { fill: BLUE, stroke: BLUE, sw: 1.2 });
  f.text(302, 234, '128 bytes', { size: 13, fill: BLUE });
  f.text(0, 262, 'the memory system moved', { size: 14, fill: INK });
  f.solid(228, 249, 288, 16, { fill: ORANGE, stroke: ORANGE, sw: 1.2 });
  f.text(524, 262, '1024 bytes', { size: 13, fill: ORANGE });
  f.text(0, 290, '32 separate sectors, and 7/8 of every one is thrown away', { size: 13, fill: MUTED });
  return f.toSVG('Naive kernel: one warp reads 32 different rows of A, moving 1024 bytes to deliver 128');
}

// ---------------------------------------------------------------- figure B
// The register outer product: 16 loads buy 64 FMAs.
function outerProduct() {
  const f = fig(740, 310, 5);
  f.text(0, 16, 'one thread, one step of k', { size: 13, fill: MUTED });

  // regM down the left
  f.text(4, 44, 'regM', { size: 14, fill: BLUE });
  f.text(0, 60, '8 from A', { size: 11, fill: MUTED });
  for (let i = 0; i < 8; i++) {
    f.solid(56, 76 + i * 24, 22, 20, { fill: BLUE, stroke: BLUE, sw: 1.2 });
  }
  // regN across the top
  f.text(92, 44, 'regN', { size: 14, fill: ORANGE });
  f.text(140, 44, '8 from B', { size: 11, fill: MUTED });
  for (let j = 0; j < 8; j++) {
    f.solid(92 + j * 24, 52, 20, 20, { fill: ORANGE, stroke: ORANGE, sw: 1.2 });
  }
  // the 8x8 accumulator grid, hatched
  f.rect(92, 76, 188, 188, { fill: BLUE, fillStyle: 'hachure', hachureGap: 7, hachureAngle: -45, sw: 1.5 });
  for (let i = 1; i < 8; i++) {
    f.line(92 + i * 23.5, 76, 92 + i * 23.5, 264, { stroke: '#b8cdea', sw: 0.8, roughness: 0.6 });
    f.line(92, 76 + i * 23.5, 280, 76 + i * 23.5, { stroke: '#b8cdea', sw: 0.8, roughness: 0.6 });
  }

  f.arrow(300, 120, 340, 120, { stroke: INK, sw: 1.2 });
  f.text(352, 112, '16 values loaded', { size: 15, fill: INK });
  f.text(352, 134, '64 multiply-adds', { size: 15, fill: INK });
  f.text(352, 156, '0.25 loads per FMA', { size: 15, fill: BLUE });

  f.line(352, 176, 700, 176, { stroke: FAINT, sw: 1 });
  f.text(352, 202, 'rung 3: 1 output/thread', { size: 13, fill: MUTED });
  f.text(600, 202, '2.00', { size: 13, fill: ORANGE, anchor: 'end' });
  f.text(352, 224, 'rung 4: 8x1 per thread', { size: 13, fill: MUTED });
  f.text(600, 224, '1.13', { size: 13, fill: MUTED });
  f.text(352, 246, 'rung 5: 8x8 per thread', { size: 13, fill: MUTED });
  f.text(600, 246, '0.25', { size: 13, fill: BLUE });
  f.text(620, 202, 'loads', { size: 11, fill: MUTED });
  f.text(620, 214, 'per FMA', { size: 11, fill: MUTED });

  f.text(0, 296, 'the 64 running sums live in registers and never touch memory until the end', { size: 13, fill: MUTED });
  return f.toSVG('Register outer product: 16 loaded values produce 64 multiply-adds');
}

const A = naiveAccess();
const B = outerProduct();

const md = `title: Figure style test — crisp vs hand-drawn
date: Scratch
author: Shashwat Pandey

---

*Scratch page for picking a figure style. Two figures, each drawn both ways. The
hand-drawn versions are generated by a script (roughjs, the same library
Excalidraw uses) so they are inline SVG with no image assets and no GUI step.*

## A. Naive memory access

**Hand-drawn (Excalidraw style, roughjs)**

<figure>
${A}
<figcaption>The naive kernel's fatal flaw. The warp wants 32 floats; because they sit in 32 different rows, the hardware moves 1024 bytes to deliver 128.</figcaption>
</figure>

**Crisp (what Part 1 ships today)**

<figure>
<svg viewBox="0 0 740 190" role="img" aria-label="Crisp version for comparison">
  <text x="0" y="14" font-family="monospace" font-size="11" fill="#666">MATRIX A IN MEMORY (ROW-MAJOR)</text>
  <text x="0" y="46" font-family="monospace" font-size="10.5" fill="#666">row 0</text>
  <rect x="52" y="34" width="600" height="14" fill="#eef1f3" stroke="#dfe3e6"/>
  <rect x="172" y="34" width="14" height="14" fill="#c2410c"/>
  <text x="664" y="46" font-family="monospace" font-size="10" fill="#c2410c">fetch 1</text>
  <text x="0" y="68" font-family="monospace" font-size="10.5" fill="#666">row 1</text>
  <rect x="52" y="56" width="600" height="14" fill="#eef1f3" stroke="#dfe3e6"/>
  <rect x="172" y="56" width="14" height="14" fill="#c2410c"/>
  <text x="664" y="68" font-family="monospace" font-size="10" fill="#c2410c">fetch 2</text>
  <text x="0" y="90" font-family="monospace" font-size="10.5" fill="#666">row 31</text>
  <rect x="52" y="78" width="600" height="14" fill="#eef1f3" stroke="#dfe3e6"/>
  <rect x="172" y="78" width="14" height="14" fill="#c2410c"/>
  <text x="664" y="90" font-family="monospace" font-size="10" fill="#c2410c">fetch 32</text>
  <rect x="0" y="118" width="720" height="26" fill="#fbeae4" stroke="#e8c4b4"/>
  <text x="8" y="135" font-family="monospace" font-size="10.5" fill="#7a2d0c">1024 bytes moved to deliver 128 &#183; 7/8 wasted</text>
  <text x="0" y="172" font-family="monospace" font-size="10.5" fill="#666">Measured: 0.112 TFLOPS, ~15 GB/s useful out of 227 GB/s available.</text>
</svg>
<figcaption>Same content, crisp.</figcaption>
</figure>

## B. The register outer product

**Hand-drawn (Excalidraw style, roughjs)**

<figure>
${B}
<figcaption>Load 8 values of A and 8 of B into registers, then do every pairwise product: 16 loads buy 64 multiply-adds.</figcaption>
</figure>

**Crisp (what Part 1 ships today)** — see section 6 of
[Part 1](blog.html?post=cuda_gemm) for the shipped version of this one.

## Notes

The hand-drawn figures use the site's validated palette rather than Excalidraw's
defaults: blue and orange as the two real hues, plus a neutral. Green is
deliberately absent — paired with orange it measured &#916;E 7.0 under
deuteranopia, which is exactly the red/green trap, and in these figures those
colors mean "fast" and "slow".

The hand font falls back through Virgil, Excalifont, Architects Daughter and
Comic Sans. If none are installed the text renders in the default cursive face,
which is the one thing that would need a webfont to fix properly.
`;

const out = path.join(__dirname, '..', 'posts', 'figtest.md');
fs.writeFileSync(out, md);

// same guards the Part 1 lesson produced
const figs = md.match(/<figure>[\s\S]*?<\/figure>/g) || [];
const blanks = figs.reduce((n, f) => n + f.split('\n').filter(l => l.trim() === '').length, 0);
const deep = figs.reduce((n, f) => n + f.split('\n').filter(l => l.length - l.trimStart().length >= 4).length, 0);
console.log(`  wrote ${out}`);
console.log(`  figures: ${figs.length}  blank lines inside: ${blanks}  lines indented >=4: ${deep}`);
